export const PLUGIN_NAME = "@kenanlian/opencode-agent-orchestrator"
export const LEGACY_PLUGIN_NAME = "oh-my-opencode"
export const CONFIG_BASENAME = "opencode-agent-orchestrator"
export const LEGACY_CONFIG_BASENAME = "oh-my-opencode"
export const LOG_FILENAME = "opencode-agent-orchestrator.log"
export const CACHE_DIR_NAME = "opencode-agent-orchestrator"
